<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "blog_articles".
 *
 * @property integer $id
 * @property integer $author_id
 * @property string $title
 * @property string $date
 * @property string $author
 * @property string $image
 * @property string $small_image
 * @property string $content
 * @property string $share_buttons
 */
class BlogArticles extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog_articles';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['author_id'], 'integer'],
            [['date'], 'safe'],
            [['content'], 'string'],
            [['title', 'author', 'image', 'small_image', 'share_buttons'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'author_id' => 'Author ID',
            'title' => 'Title',
            'date' => 'Date',
            'author' => 'Author',
            'image' => 'Image',
            'small_image' => 'Small Image',
            'content' => 'Content',
            'share_buttons' => 'Share Buttons',
        ];
    }
    
    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $this->author_id = Yii::$app->user->identity->id;
            $this->author = Yii::$app->user->identity->name;
            $this->date = date('Y-m-d');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
