<?php

namespace frontend\models;

use Yii;

/**
 * This is the model class for table "groups".
 *
 * @property integer $id
 * @property integer $trainer_creator_id
 * @property string $title
 * @property string $registration_date
 * @property string $trainers_ids
 * @property string $group_users_ids
 * @property string $small_image
 * @property string $image
 * @property string $content
 * @property string $share_buttons
 */
class Groups extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'groups';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['trainer_creator_id'], 'integer'],
            [['registration_date'], 'safe'],
            [['content'], 'string'],
            [['title', 'trainers_ids', 'group_users_ids', 'small_image', 'image', 'share_buttons'], 'string', 'max' => 255],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'trainer_creator_id' => 'Trainer Creator ID',
            'title' => 'Title',
            'registration_date' => 'Registration Date',
            'trainers_ids' => 'Trainers Ids',
            'group_users_ids' => 'Group Users Ids',
            'small_image' => 'Small Image',
            'image' => 'Image',
            'content' => 'Content',
            'share_buttons' => 'Share Buttons',
        ];
    }
    
    public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $this->trainer_creator_id = yii::$app->user->identity->id;
            $this->registration_date = date('Y-m-d');
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
