<?php

namespace frontend\models;

use Yii;
use yii\web\UploadedFile;

/**
 * This is the model class for table "user".
 *

 * @property string $email
 * @property string $name
 * @property string $surname
 * @property string $about_info
 * @property integer $age
 * @property string $sex
 * @property string $phone
 * @property string $time_for_training
 * @property string $avatar
 * @property integer $rating
 * @property string $city
 * @property string $type_of_sport
 * @property string $competitions
 * @property integer $price
 * @property string $training_sex
 * @property string $group_training
 * @property integer $price_per_group_training
 * @property string $achievements
 * @property string $place_of_training
 * @property string $gym_location
 * @property string $years_experience
 * @property string $previous_jobs
 * @property string $recommendations
 * @property string $role
 */
class Trainer extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['age', 'rating', 'price', 'price_per_group_training'], 'integer'],
            [['about_info', 'competitions', 'achievements', 'previous_jobs', 'recommendations'], 'string'],
            [['registration_date'], 'safe'],
            [['email', 'name', 'surname', 'sex', 'phone', 'time_for_training', 'city', 'type_of_sport', 'training_sex', 'group_training', 'place_of_training', 'gym_location', 'years_experience', 'ip'], 'string', 'max' => 255],

            [['email'], 'unique'],
            //[['avatar'], 'file','skipOnEmpty' => false, 'extensions' => 'png, jpg'],
            [['avatar'], 'file', 'extensions' => 'png, jpg'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'email' => 'Email',
            'name' => 'Name',
            'surname' => 'Surname',
            'about_info' => 'About Info',
            'age' => 'Age',
            'sex' => 'Sex',
            'phone' => 'Phone',
            'time_for_training' => 'Time For Training',
            'registration_date' => 'Registration Date',
            'avatar' => 'Avatar',
            'rating' => 'Rating',
            'city' => 'City',
            'type_of_sport' => 'Type Of Sport',
            'competitions' => 'Competitions',
            'price' => 'Price',
            'training_sex' => 'Training Sex',
            'group_training' => 'Group Training',
            'price_per_group_training' => 'Price Per Group Training',
            'achievements' => 'Achievements',
            'place_of_training' => 'Place Of Training',
            'gym_location' => 'Gym Location',
            'years_experience' => 'Years Experience',
            'previous_jobs' => 'Previous Jobs',
            'recommendations' => 'Recommendations',
            'ip' => 'Ip',
        ];
    }

    /**
     * @param bool $insert
     * @return bool
     */
    /*public function beforeSave($insert)
    {
        if ($this->isNewRecord){
            $this->avatar=UploadedFile::getInstance($this, 'avatar');
            $file_string = 'trainer/avatar/' . $this->avatar->baseName . Yii::$app->user->identity->id . $this->avatar->extension;
            $this->avatar->saveAs($file_string);
            $this->avatar = $file_string;
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    } */


}
